spring:
  application:
    name: faculdadeprojeto

  datasource:
    url: jdbc:h2:mem:faculdadeprojeto;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
