spring:
  application:
    name: faculdadeprojeto
  datasource:
    url: jdbc:h2:mem:faculdadeprojeto
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true